// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// alexandrov_topology_engine
Rcpp::List alexandrov_topology_engine(Rcpp::List out_adjacency, int n_elements, int max_open_sets, bool enumerate_topology, bool check_connected, bool verify_axioms);
RcppExport SEXP _topologyR_alexandrov_topology_engine(SEXP out_adjacencySEXP, SEXP n_elementsSEXP, SEXP max_open_setsSEXP, SEXP enumerate_topologySEXP, SEXP check_connectedSEXP, SEXP verify_axiomsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type out_adjacency(out_adjacencySEXP);
    Rcpp::traits::input_parameter< int >::type n_elements(n_elementsSEXP);
    Rcpp::traits::input_parameter< int >::type max_open_sets(max_open_setsSEXP);
    Rcpp::traits::input_parameter< bool >::type enumerate_topology(enumerate_topologySEXP);
    Rcpp::traits::input_parameter< bool >::type check_connected(check_connectedSEXP);
    Rcpp::traits::input_parameter< bool >::type verify_axioms(verify_axiomsSEXP);
    rcpp_result_gen = Rcpp::wrap(alexandrov_topology_engine(out_adjacency, n_elements, max_open_sets, enumerate_topology, check_connected, verify_axioms));
    return rcpp_result_gen;
END_RCPP
}
// generate_topology_engine
Rcpp::List generate_topology_engine(Rcpp::List adjacency, int n_elements, int max_open_sets, int max_base_sets, bool enumerate_topology, bool check_connected, bool verify_axioms);
RcppExport SEXP _topologyR_generate_topology_engine(SEXP adjacencySEXP, SEXP n_elementsSEXP, SEXP max_open_setsSEXP, SEXP max_base_setsSEXP, SEXP enumerate_topologySEXP, SEXP check_connectedSEXP, SEXP verify_axiomsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type adjacency(adjacencySEXP);
    Rcpp::traits::input_parameter< int >::type n_elements(n_elementsSEXP);
    Rcpp::traits::input_parameter< int >::type max_open_sets(max_open_setsSEXP);
    Rcpp::traits::input_parameter< int >::type max_base_sets(max_base_setsSEXP);
    Rcpp::traits::input_parameter< bool >::type enumerate_topology(enumerate_topologySEXP);
    Rcpp::traits::input_parameter< bool >::type check_connected(check_connectedSEXP);
    Rcpp::traits::input_parameter< bool >::type verify_axioms(verify_axiomsSEXP);
    rcpp_result_gen = Rcpp::wrap(generate_topology_engine(adjacency, n_elements, max_open_sets, max_base_sets, enumerate_topology, check_connected, verify_axioms));
    return rcpp_result_gen;
END_RCPP
}
// is_connected_exact_cpp
Rcpp::List is_connected_exact_cpp(Rcpp::List topology_sets, int n_elements);
RcppExport SEXP _topologyR_is_connected_exact_cpp(SEXP topology_setsSEXP, SEXP n_elementsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type topology_sets(topology_setsSEXP);
    Rcpp::traits::input_parameter< int >::type n_elements(n_elementsSEXP);
    rcpp_result_gen = Rcpp::wrap(is_connected_exact_cpp(topology_sets, n_elements));
    return rcpp_result_gen;
END_RCPP
}
// hvg_cpp
Rcpp::List hvg_cpp(Rcpp::NumericVector y);
RcppExport SEXP _topologyR_hvg_cpp(SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(hvg_cpp(y));
    return rcpp_result_gen;
END_RCPP
}
// nvg_cpp
Rcpp::List nvg_cpp(Rcpp::NumericVector y);
RcppExport SEXP _topologyR_nvg_cpp(SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(nvg_cpp(y));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_topologyR_alexandrov_topology_engine", (DL_FUNC) &_topologyR_alexandrov_topology_engine, 6},
    {"_topologyR_generate_topology_engine", (DL_FUNC) &_topologyR_generate_topology_engine, 7},
    {"_topologyR_is_connected_exact_cpp", (DL_FUNC) &_topologyR_is_connected_exact_cpp, 2},
    {"_topologyR_hvg_cpp", (DL_FUNC) &_topologyR_hvg_cpp, 1},
    {"_topologyR_nvg_cpp", (DL_FUNC) &_topologyR_nvg_cpp, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_topologyR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
