# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

alexandrov_topology_engine <- function(out_adjacency, n_elements, max_open_sets = 0L, enumerate_topology = FALSE, check_connected = TRUE, verify_axioms = FALSE) {
    .Call(`_topologyR_alexandrov_topology_engine`, out_adjacency, n_elements, max_open_sets, enumerate_topology, check_connected, verify_axioms)
}

generate_topology_engine <- function(adjacency, n_elements, max_open_sets = 1000000L, max_base_sets = 100000L, enumerate_topology = TRUE, check_connected = TRUE, verify_axioms = FALSE) {
    .Call(`_topologyR_generate_topology_engine`, adjacency, n_elements, max_open_sets, max_base_sets, enumerate_topology, check_connected, verify_axioms)
}

is_connected_exact_cpp <- function(topology_sets, n_elements) {
    .Call(`_topologyR_is_connected_exact_cpp`, topology_sets, n_elements)
}

hvg_cpp <- function(y) {
    .Call(`_topologyR_hvg_cpp`, y)
}

nvg_cpp <- function(y) {
    .Call(`_topologyR_nvg_cpp`, y)
}

